USE [TestPizzaImport]
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='BULKPIZZADATA_ARCHIVE' AND xtype='U')
    CREATE TABLE BULKPIZZADATA_ARCHIVE([FIRSTNAME] NVARCHAR(100) NOT NULL, [MIDDLEINITIAL] NVARCHAR(5) NULL,
[LASTNAME] NVARCHAR(100) NOT NULL, [PHONENUMBER] NVARCHAR(12) NOT NULL, [HOMEADDRESS] NVARCHAR(200) NOT NULL,
[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL,
[ITEMNAME] NVARCHAR(100) NOT NULL, [ITEMQUANTITY] NVARCHAR(5) NOT NULL, [ITEMUNITPRICE] NVARCHAR(10) NOT NULL,
[ITEMPRICEXQUANTITY] NVARCHAR(15) NOT NULL, [ORDERTOTAL] NVARCHAR(16) NOT NULL, [ORDERNOTES] NVARCHAR(MAX) NULL, 
[ORDERDATETIME] NVARCHAR(20) NOT NULL, [IMPORTDATE] DATETIME NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_BULKPIZZADATA' AND xtype='U')
    CREATE TABLE IMPORT_BULKPIZZADATA([FIRSTNAME] NVARCHAR(100) NOT NULL, [MIDDLEINITIAL] NVARCHAR(5) NULL,
[LASTNAME] NVARCHAR(100) NOT NULL, [PHONENUMBER] NVARCHAR(12) NOT NULL, [HOMEADDRESS] NVARCHAR(200) NOT NULL,
[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL,
[ITEMNAME] NVARCHAR(100) NOT NULL, [ITEMQUANTITY] NVARCHAR(5) NOT NULL, [ITEMUNITPRICE] NVARCHAR(10) NOT NULL,
[ITEMPRICEXQUANTITY] NVARCHAR(15) NOT NULL, [ORDERTOTAL] NVARCHAR(16) NOT NULL, [ORDERNOTES] NVARCHAR(MAX) NULL, 
[ORDERDATETIME] NVARCHAR(20) NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_CUSTOMERDATA' AND xtype='U')
CREATE TABLE IMPORT_CUSTOMERDATA ([FIRSTNAME] NVARCHAR(100) NOT NULL, [MIDDLEINITIAL] NVARCHAR(5) NULL,
[LASTNAME] NVARCHAR(100) NOT NULL, [PHONENUMBER] NVARCHAR(12) NOT NULL, [HOMEADDRESS] NVARCHAR(200) NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_MENUDATA' AND xtype='U')
CREATE TABLE IMPORT_MENUDATA ([ITEMNAME] NVARCHAR(100) NOT NULL, [ITEMUNITPRICE] NVARCHAR(10) NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_ORDERITEMDATA' AND xtype='U')
CREATE TABLE IMPORT_ORDERITEMDATA ([ITEMNAME] NVARCHAR(100) NOT NULL, [ITEMQUANTITY] NVARCHAR(5) NOT NULL, 
[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL, [ITEMUNITPRICE] NVARCHAR(10) NOT NULL,
[ITEMPRICEXQUANTITY] NVARCHAR(15) NOT NULL, [ORDERDATETIME] NVARCHAR(20) NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_INDIVIDUALORDERDATA' AND xtype='U')
CREATE TABLE IMPORT_INDIVIDUALORDERDATA([FIRSTNAME] NVARCHAR(100) NOT NULL, [MIDDLEINITIAL] NVARCHAR(5) NULL,
[LASTNAME] NVARCHAR(100) NOT NULL, [PHONENUMBER] NVARCHAR(12) NOT NULL, [HOMEADDRESS] NVARCHAR(200) NOT NULL,
[ORDERTOTAL] NVARCHAR(16) NOT NULL, [ORDERNOTES] NVARCHAR(MAX) NULL, [ORDERDATETIME] NVARCHAR(20) NOT NULL);
GO


IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='CUSTOMERS' AND xtype='U')
CREATE TABLE CUSTOMERS ([CUSTOMERID] NVARCHAR(8) NOT NULL PRIMARY KEY, [FIRSTNAME] NVARCHAR(100) NOT NULL, [MIDDLEINITIAL] NVARCHAR(5) NULL,
[LASTNAME] NVARCHAR(100) NOT NULL, [PHONENUMBER] NVARCHAR(12) NOT NULL, [HOMEADDRESS] NVARCHAR(200) NOT NULL,
[CUSTOMERNOTES] TEXT NULL, [RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1));
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='MENU' AND xtype='U')
CREATE TABLE MENU ([ITEMID] NVARCHAR(5) NOT NULL PRIMARY KEY, [ITEMNAME] NVARCHAR(100) NOT NULL, [ITEMUNITPRICE] MONEY NOT NULL, 
[ITEMNOTES] TEXT NULL, [RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1));
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='ORDEREDITEMS' AND xtype='U')
CREATE TABLE ORDEREDITEMS ([ORDERID] NVARCHAR(9) NOT NULL, [ITEMID] NVARCHAR(5) NOT NULL, 
[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL, [ITEMQUANTITY] NUMERIC(5,0) NOT NULL,
[ITEMPRICEXQUANTITY] MONEY NOT NULL);
GO

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='ORDERS' AND xtype='U')
CREATE TABLE ORDERS([ORDERID] NVARCHAR(9) NOT NULL PRIMARY KEY, [CUSTOMERID] NVARCHAR(8) NOT NULL,
[ORDERTOTAL] NVARCHAR(16) NOT NULL, [ORDERNOTES] NVARCHAR(MAX) NULL, [ORDERDATETIME] DATETIME NOT NULL, 
[RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1));
GO