USE [TESTPIZZAIMPORT]
GO


BULK INSERT IMPORT_BULKPIZZADATA FROM $(IMPORTFILE)
WITH (FIRSTROW = 2, FIELDTERMINATOR = '\t', ROWTERMINATOR = '\n');

INSERT INTO [dbo].[IMPORT_CUSTOMERDATA]
           ([FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS])
     SELECT [FIRSTNAME], [MIDDLEINITIAL], [LASTNAME], [PHONENUMBER], [HOMEADDRESS] FROM IMPORT_BULKPIZZADATA
	 WHERE [FIRSTNAME] IS NOT NULL AND [LASTNAME] IS NOT NULL AND [PHONENUMBER] IS NOT NULL AND [HOMEADDRESS] IS NOT NULL;

INSERT INTO [dbo].[IMPORT_INDIVIDUALORDERDATA]
           ([FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS]
           ,[ORDERTOTAL]
           ,[ORDERNOTES]
           ,[ORDERDATETIME])
    SELECT [FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS]
           ,[ORDERTOTAL]
           ,[ORDERNOTES]
           ,[ORDERDATETIME]
		   FROM IMPORT_BULKPIZZADATA
		   WHERE [FIRSTNAME] IS NOT NULL AND [LASTNAME] IS NOT NULL 
		   AND [PHONENUMBER] IS NOT NULL AND [HOMEADDRESS] IS NOT NULL
		   AND [ORDERDATETIME] IS NOT NULL;


INSERT INTO [dbo].[IMPORT_MENUDATA]
           ([ITEMNAME]
           ,[ITEMUNITPRICE])
     SELECT [ITEMNAME]
           ,[ITEMUNITPRICE]
		   FROM IMPORT_BULKPIZZADATA 
		   WHERE [ITEMNAME] IS NOT NULL
		   AND [ITEMUNITPRICE] IS NOT NULL;


INSERT INTO [dbo].[IMPORT_ORDERITEMDATA]
           ([ITEMNAME]
           ,[ITEMQUANTITY]
		   ,[ITEMLINEITEMNUMBER]
           ,[ITEMUNITPRICE]
           ,[ITEMPRICEXQUANTITY]
           ,[ORDERDATETIME])
    SELECT [ITEMNAME]
           ,[ITEMQUANTITY]
		   ,[ITEMLINEITEMNUMBER]
           ,[ITEMUNITPRICE]
           ,[ITEMPRICEXQUANTITY]
           ,[ORDERDATETIME]
		   FROM IMPORT_BULKPIZZADATA
		   WHERE [ITEMNAME] IS NOT NULL
		   AND [ITEMUNITPRICE] IS NOT NULL
		   AND [ITEMLINEITEMNUMBER] IS NOT NULL
		   AND [ITEMPRICEXQUANTITY] IS NOT NULL
		   AND [ORDERDATETIME] IS NOT NULL;
