USE [TestPizzaImport]
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES 
               WHERE ROUTINE_NAME = 'SetupPizzaInformationStore'
			   AND ROUTINE_SCHEMA = 'dbo'
			   AND ROUTINE_TYPE = 'PROCEDURE')
			       EXEC ('DROP PROCEDURE dbo.SetupPizzaInformationStore')
GO

CREATE PROCEDURE SetupPizzaInformationStore
AS
SET NOCOUNT ON
BEGIN
IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='BULKPIZZADATA_ARCHIVE' AND xtype='U')
    CREATE TABLE BULKPIZZADATA_ARCHIVE([FIRSTNAME] NVARCHAR(102) NOT NULL 
	                                   ,[MIDDLEINITIAL] NVARCHAR(5) NULL
                                       ,[LASTNAME] NVARCHAR(102) NOT NULL 
									   ,[PHONENUMBER] NVARCHAR(14) NOT NULL 
									   ,[HOMEADDRESS] NVARCHAR(202) NOT NULL
                                       ,[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL
                                       ,[ITEMNAME] NVARCHAR(102) NOT NULL 
									   ,[ITEMQUANTITY] NVARCHAR(5) NOT NULL 
									   ,[ITEMUNITPRICE] NVARCHAR(11) NOT NULL
                                       ,[ITEMPRICEXQUANTITY] NVARCHAR(14) NOT NULL 
									   ,[ORDERTOTAL] NVARCHAR(18) NOT NULL 
									   ,[ORDERNOTES] NVARCHAR(MAX) NULL 
                                       ,[ORDERDATETIME] NVARCHAR(20) NOT NULL 
									   ,[IMPORTDATE] DATETIME NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_BULKPIZZADATA' AND xtype='U')
    CREATE TABLE IMPORT_BULKPIZZADATA([FIRSTNAME] NVARCHAR(102) NOT NULL 
	                                  ,[MIDDLEINITIAL] NVARCHAR(5) NULL
                                      ,[LASTNAME] NVARCHAR(102) NOT NULL
									  ,[PHONENUMBER] NVARCHAR(14) NOT NULL 
									  ,[HOMEADDRESS] NVARCHAR(202) NOT NULL
                                      ,[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL
                                      ,[ITEMNAME] NVARCHAR(102) NOT NULL
									  ,[ITEMQUANTITY] NVARCHAR(5) NOT NULL
									  ,[ITEMUNITPRICE] NVARCHAR(11) NOT NULL
                                      ,[ITEMPRICEXQUANTITY] NVARCHAR(14) NOT NULL 
									  ,[ORDERTOTAL] NVARCHAR(18) NOT NULL
									  ,[ORDERNOTES] NVARCHAR(MAX) NULL
                                      ,[ORDERDATETIME] NVARCHAR(20) NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_CUSTOMERDATA' AND xtype='U')
    CREATE TABLE IMPORT_CUSTOMERDATA ([FIRSTNAME] NVARCHAR(100) NOT NULL 
	                                  ,[MIDDLEINITIAL] NVARCHAR(5) NULL
                                      ,[LASTNAME] NVARCHAR(100) NOT NULL 
									  ,[PHONENUMBER] NVARCHAR(12) NOT NULL 
									  ,[HOMEADDRESS] NVARCHAR(200) NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_MENUDATA' AND xtype='U')
    CREATE TABLE IMPORT_MENUDATA ([ITEMNAME] NVARCHAR(100) NOT NULL 
	                              ,[ITEMUNITPRICE] NVARCHAR(10) NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_ORDERITEMDATA' AND xtype='U')
    CREATE TABLE IMPORT_ORDERITEMDATA ([ITEMNAME] NVARCHAR(100) NOT NULL 
	                                   ,[ITEMQUANTITY] NVARCHAR(5) NOT NULL 
                                       ,[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL
									   ,[ITEMUNITPRICE] NVARCHAR(10) NOT NULL
                                       ,[ITEMPRICEXQUANTITY] NVARCHAR(15) NOT NULL 
									   ,[ORDERDATETIME] NVARCHAR(20) NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='IMPORT_INDIVIDUALORDERDATA' AND xtype='U')
    CREATE TABLE IMPORT_INDIVIDUALORDERDATA([FIRSTNAME] NVARCHAR(100) NOT NULL 
	                                        ,[MIDDLEINITIAL] NVARCHAR(5) NULL
                                            ,[LASTNAME] NVARCHAR(100) NOT NULL 
											,[PHONENUMBER] NVARCHAR(12) NOT NULL 
											,[HOMEADDRESS] NVARCHAR(200) NOT NULL
                                            ,[ORDERTOTAL] NVARCHAR(16) NOT NULL 
											,[ORDERNOTES] NVARCHAR(MAX) NULL 
											,[ORDERDATETIME] NVARCHAR(20) NOT NULL);

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='CUSTOMERS' AND xtype='U')
    CREATE TABLE CUSTOMERS ([CUSTOMERID] NVARCHAR(8) NOT NULL PRIMARY KEY 
	                        ,[FIRSTNAME] NVARCHAR(100) NOT NULL 
							,[MIDDLEINITIAL] NVARCHAR(5) NULL
                            ,[LASTNAME] NVARCHAR(100) NOT NULL 
							,[PHONENUMBER] NVARCHAR(12) NOT NULL 
							,[HOMEADDRESS] NVARCHAR(200) NOT NULL
                            ,[CUSTOMERNOTES] NVARCHAR(MAX) NULL
							,[RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1));

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='MENU' AND xtype='U')
    CREATE TABLE MENU ([ITEMID] NVARCHAR(5) NOT NULL PRIMARY KEY 
	                   ,[ITEMNAME] NVARCHAR(100) NOT NULL
					   ,[ITEMUNITPRICE] MONEY NOT NULL
                       ,[ITEMNOTES] NVARCHAR(MAX) NULL 
					   ,[RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1));

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='ORDERS' AND xtype='U')
    CREATE TABLE ORDERS([ORDERID] NVARCHAR(9) NOT NULL PRIMARY KEY 
	                    ,[CUSTOMERID] NVARCHAR(8) NOT NULL
                        ,[ORDERTOTAL] NVARCHAR(16) NOT NULL 
						,[ORDERNOTES] NVARCHAR(MAX) NULL 
						,[ORDERDATETIME] DATETIME NOT NULL
                        ,[RECORDNUMBER] NUMERIC NOT NULL IDENTITY(1,1)
						,FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID));

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE name='ORDEREDITEMS' AND xtype='U')
    CREATE TABLE ORDEREDITEMS ([ORDERID] NVARCHAR(9) NOT NULL
	                           ,[ITEMID] NVARCHAR(5) NOT NULL 
                               ,[ITEMLINEITEMNUMBER] NVARCHAR(6) NOT NULL, [ITEMQUANTITY] NUMERIC(5,0) NOT NULL
                               ,[ITEMPRICEXQUANTITY] MONEY NOT NULL
							   ,FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID)
							   ,FOREIGN KEY (ITEMID) REFERENCES MENU(ITEMID));
END