USE [PIZZALOGISTICS]
GO
/****** Object:  StoredProcedure [dbo].[BULKPIZZADATA_RAWIMPORT]    Script Date: 5/14/2020 4:50:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES 
               WHERE ROUTINE_NAME = 'BULKPIZZADATA_RAWIMPORT'
			   AND ROUTINE_SCHEMA = 'dbo'
			   AND ROUTINE_TYPE = 'PROCEDURE')
			       EXEC ('DROP PROCEDURE dbo.BULKPIZZADATA_RAWIMPORT')
GO

CREATE PROCEDURE [dbo].[BULKPIZZADATA_RAWIMPORT] @FILENAME NVARCHAR(256)
AS
SET NOCOUNT ON
BEGIN
DECLARE @SANITIZEDINPUT AS NVARCHAR(MAX);
DECLARE @EXECSTATEMENT AS NVARCHAR(MAX);


SET @SANITIZEDINPUT = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@FILENAME,'''',''),'$',''),'=',''),'-',''),'/',''),'*',''),'%',''),'@',''),'^','');
SET @EXECSTATEMENT = 'BULK INSERT IMPORT_BULKPIZZADATA FROM ''' + @SANITIZEDINPUT + '''
WITH (FIRSTROW = 2, FIELDTERMINATOR = ''\t'', ROWTERMINATOR = ''\n'');';

EXEC (@EXECSTATEMENT);

INSERT INTO [dbo].[IMPORT_CUSTOMERDATA]
           ([FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS])
     SELECT [FIRSTNAME], [MIDDLEINITIAL], [LASTNAME], [PHONENUMBER], [HOMEADDRESS] FROM IMPORT_BULKPIZZADATA
	 WHERE [FIRSTNAME] IS NOT NULL AND [LASTNAME] IS NOT NULL AND [PHONENUMBER] IS NOT NULL AND [HOMEADDRESS] IS NOT NULL;

INSERT INTO [dbo].[IMPORT_INDIVIDUALORDERDATA]
           ([FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS]
           ,[ORDERTOTAL]
           ,[ORDERNOTES]
           ,[ORDERDATETIME])
    SELECT [FIRSTNAME]
           ,[MIDDLEINITIAL]
           ,[LASTNAME]
           ,[PHONENUMBER]
           ,[HOMEADDRESS]
           ,[ORDERTOTAL]
           ,[ORDERNOTES]
           ,[ORDERDATETIME]
		   FROM IMPORT_BULKPIZZADATA
		   WHERE [FIRSTNAME] IS NOT NULL AND [LASTNAME] IS NOT NULL 
		   AND [PHONENUMBER] IS NOT NULL AND [HOMEADDRESS] IS NOT NULL
		   AND [ORDERDATETIME] IS NOT NULL;


INSERT INTO [dbo].[IMPORT_MENUDATA]
           ([ITEMNAME]
           ,[ITEMUNITPRICE])
     SELECT [ITEMNAME]
           ,[ITEMUNITPRICE]
		   FROM IMPORT_BULKPIZZADATA 
		   WHERE [ITEMNAME] IS NOT NULL
		   AND [ITEMUNITPRICE] IS NOT NULL;


INSERT INTO [dbo].[IMPORT_ORDERITEMDATA]
           ([ITEMNAME]
           ,[ITEMQUANTITY]
		   ,[ITEMLINEITEMNUMBER]
           ,[ITEMUNITPRICE]
           ,[ITEMPRICEXQUANTITY]
           ,[ORDERDATETIME])
    SELECT [ITEMNAME]
           ,[ITEMQUANTITY]
		   ,[ITEMLINEITEMNUMBER]
           ,[ITEMUNITPRICE]
           ,[ITEMPRICEXQUANTITY]
           ,[ORDERDATETIME]
		   FROM IMPORT_BULKPIZZADATA
		   WHERE [ITEMNAME] IS NOT NULL
		   AND [ITEMUNITPRICE] IS NOT NULL
		   AND [ITEMLINEITEMNUMBER] IS NOT NULL
		   AND [ITEMPRICEXQUANTITY] IS NOT NULL
		   AND [ORDERDATETIME] IS NOT NULL;

END